database:
  url: "jdbc:sqlite:..\\database\\QuestSystemDB.sqlite"

npc-location:
  x: 65.5
  y: 143
  z: 57.5

npc-settings:
  type: VILLAGER
  custom-name: Quests
  custom-name-visible: true
  invulnerable: true
  ai-enabled: false
  max-health: 1000.0

npc-task:
  interval: 1
  range: 15

inventory:
  back:
    display-name: "Back"
    colour: "#FFFFFF"
  switch-page:
    success:
      sound: "BLOCK_NOTE_BLOCK_PLING"
      volume: 1
      pitch: 1
    error:
      sound: "BLOCK_NOTE_BLOCK_BASS"
      volume: 1
      pitch: 1
  next-page:
    display-name: "Next Page: %page%"
    colour: "#FFFFFF"
  prev-page:
    display-name: "Previous Page: %page%"
    colour: "#FFFFFF"
  create-quest:
    display-name: "Create Quest"
    colour: "#00FF00"
    material: CHEST
    default:
      name: "Quest Name"
      description: "Quest Description"
      time-limit: 10
    error-message: "Please enter a new name for the quest"
  create-reward:
    display-name: "Create Reward"
    colour: "#00FF00"
    material: CHEST
    default:
      name: "Reward Name"
      amount: 1
      reward-type-id: 1
      value: "ENTER A VALUE (STONE)"
    error-message: "Please enter a new name for the reward"
  create-objective:
    display-name: "Create Objective"
    colour: "#00FF00"
    material: CHEST
    default:
      name: "Objective Name"
      count: 1
      type: "KILL"
      value: "ENTER A VALUE (ZOMBIE)"
    error-message: "Please enter a new objective for the objective"
  edit-quest:
    name:
      title: "Quest Name"
      colour: "#FFCC00"
      material: "NAME_TAG"
      change-message: "Enter the new name for the quest"
    description:
      title: "Quest Description"
      colour: "#3399FF"
      material: "PAPER"
      change-message: "Enter the new description for the quest"
    objective:
      title: "Quest Objective"
      colour: "#FF6666"
      material: "TRAPPED_CHEST"
      change-message: "Select or edit a Objective"
    time-limit:
      title: "Time Limit"
      colour: "#99CC00"
      material: "CLOCK"
      change-message: "Enter the new time limit for the quest"
    rewards:
      title: "Quest Rewards"
      colour: "#FF9900"
      material: "CHEST"
      change-message: "Select or edit a Reward"
    save:
      title: "Save Changes"
      colour: "#66CC99"
      material: "GREEN_WOOL"
    cancel:
      title: "Cancel Edit"
      colour: "#FF3366"
      material: "RED_WOOL"
    no-objective:
      title: "Select a Objective"
      colour: "#FF6666"
  edit-reward: #EMERALD not allowed as Material
    name:
      title: "Quest Name"
      colour: "#FFCC00"
      material: "NAME_TAG"
      change-message: "Enter the new name for the quest"
    amount:
      title: "Amount"
      colour: "#FFCC00"
      material: "GOLD_INGOT"
      change-message: "Enter the new amount for the quest"
    reward-type-id:
      title: "Reward Type Id"
      colour: "#FFCC00"
      material: "PAPER"
      change-message: "Enter the new reward type id for the quest"
    value:
      title: "Value"
      colour: "#FFCC00"
      material: "BOOK"
      change-message: "Enter the new value for the quest"
    save:
      title: "Save Changes"
      colour: "#66CC99"
      material: "GREEN_WOOL"
    cancel:
      title: "Cancel Edit"
      colour: "#FF3366"
      material: "RED_WOOL"
  edit-objective:
    name:
      title: "Objective Name"
      colour: "#FFCC00"
      material: "NAME_TAG"
      change-message: "Enter the new name for the objective"
    count:
      title: "Objective Count"
      colour: "#FFCC00"
      material: "GOLD_INGOT"
      change-message: "Enter the new count for the objective"
    type:
      title: "Objective Type"
      colour: "#FF6666"
      material: "PAPER"
      change-message: "Enter the new type for the objective (KILL, PICKUP, MOVE)"
    value:
      title: "Objective Value"
      colour: "#99CC00"
      material: "CLOCK"
      change-message: "Enter the new value for the objective"
    save:
      title: "Save Changes"
      colour: "#66CC99"
      material: "GREEN_WOOL"
    cancel:
      title: "Cancel Edit"
      colour: "#FF3366"
      material: "RED_WOOL"



particle-settings:
  direction:
    particle: "PORTAL"
    spacing: 0.5
    distance: 8
    count: 10
    offset-x: 0
    offset-y: 0
    offset-z: 0
    extra: 0.1
  spawn:
    particle: "FLAME"
    iterations: 10
    count: 15
    offset-x: 0.1
    offset-y: 0.5
    offset-z: 0.1
    extra: 0.02

quest-inv:
  title: "Quests"
  colour: "#FFFFFF"

objective-inv:
  title: "Objectives"
  colour: "#FFFFFF"

reward-inv:
  title: "Rewards"
  colour: "#FFFFFF"

quest-manager:
  quest:
    edit:
      title: "Click to edit"
      colour: "#00AAFF"
    main-colour: "#FF0000"
    reactivated:
      message: "You have reactivated the quest: "
      colour: "#FFA500"
      sound:
        name: "BLOCK_NOTE_BLOCK_PLING"
        volume: 1
        pitch: 1
    canceled:
      message: "You have canceled the quest: "
      colour: "#FF0000"
      sound:
        name: "BLOCK_NOTE_BLOCK_BASS"
        volume: 1
        pitch: 1
    accepted:
      message: "You have accepted the quest: "
      colour: "#FFA500"
      sound:
        name: "BLOCK_NOTE_BLOCK_PLING"
        volume: 1
        pitch: 1
    completed:
      message: "You have completed the quest: "
      colour: "#00FF00"
      sound:
        name: "ENTITY_PLAYER_LEVELUP"
        volume: 1
        pitch: 1
      alert:
        message: "Quest Completed"
        colour: 0x008000
        fade-in: 1000
        stay: 3000
        fade-out: 1000

    failed:
      message: "You did not complete the quest: "
      colour: "#FF0000"
      sound:
        name: "BLOCK_END_PORTAL_SPAWN"
        volume: 1
        pitch: 1
      alert:
        message: "Quest Failed"
        colour: 0xFF0000
        fade-in: 1000
        stay: 3000
        fade-out: 1000
    objective: "Your objective is to: "
    rewards:
      message: "You have received "
      colour: "#00FF00"
    time-limit: " in the given time limit of "
    click-not-started: "Click to accept"
    click-in-progress: "Click to cancel"
    click-completed: "Quest Completed"
    click-canceled: "Click to try again"
    all: "All Quests"
    status:
      in-progress:
        message: "In Progress"
        color: "#FFA500" # Orange
      completed:
        message: "Completed"
        color: "#00FF00" # Green
      canceled:
        message: "Canceled"
        color: "#FF0000" # Red
      not-started:
        message: "Not Started"
        color: "#00AAFF" # White
  reward:
    edit:
      title: "Click to edit"
      colour: "#00AAFF"
    colour: "#00FF00"
    lore:
      already-assigned:
        message: "Click to unassign reward"
        colour: "#FF0000"
      click-to-assign:
        message: "Click to assign reward"
        colour: "#00FF00"
      click-to-edit:
        message: "Right-click to edit"
        colour: "#00AAFF"
      click-to-delete:
        message: "Shift-click to delete"
        colour: "#FF0000"
      name:
        message: "Name: "
        colour: "#FFCC00"
      amount:
        message: "Amount: "
        colour: "#FFCC00"
      rewardTypeId:
        message: "Reward Type Id: "
        colour: "#FFCC00"
      value:
        message: "Value: "
        colour: "#FFCC00"

  objective:
    edit:
      title: "Click to edit"
      colour: "#00AAFF"
    colour: "#00FF00"
    lore:
      click-to-edit:
        message: "Right-click to edit"
        colour: "#00AAFF"
      click-to-delete:
        message: "Shift-click to delete"
        colour: "#FF0000"
      already-assigned:
        message: "Objective already assigned"
        colour: "#FF0000"
      click-to-assign:
        message: "Click to assign objective"
        colour: "#00FF00"
      name:
        message: "Name: "
        colour: "#FFCC00"
      type:
        message: "Type: "
        colour: "#FFCC00"
      value:
        message: "Value: "
        colour: "#FFCC00"
      count:
        message: "Count: "
        colour: "#FFCC00"


  lore-entries:
    empty: ""
    status-label: "Status:"
    description-label: "Description:"
    objective-label: "Objective:"
    time-limit-label: "Time limit: "
    time-left-label: "Time left: "
    rewards-label: "Rewards:"
    rewards-colour: "#00FF00"
    edit:
      title: "Right-click to edit"
      colour: "#00AAFF"
    delete:
      title: "Shift-click to delete"
      colour: "#FF0000"
      sound: "ENTITY_ITEM_BREAK"
      volume: 1
      pitch: 1
  boss-bar:
    init:
      colour: "BLUE"
      overlay: "PROGRESS"
    complete:
      colour: "GREEN"

command:
  no-player: "Only players can use this command"

quest-system:
  welcome:
    message: "Welcome back! You have active quests, click here to see them"
    colour: "#FFA500"

sign-messages:
  quests-title: "quests"
  quest-title: "quest"
  quests_sign:
    line_0:
      text: "Quests: %size%"
      color: "#000000" # Green
    line_3:
      text: ""
      color: "#00FF00" # Green
  quest_sign:
    no_quests:
      line_0:
        text: "No quests started"
        color: "#FF0000" # Red
      line_1:
        text: ""
        color: "#FF0000" # Red
      line_2:
        text: ""
        color: "#FF0000" # Red
      line_3:
        text: ""
        color: "#FF0000" # Red
    quest:
      line_0:
        text: "Quest: %name%"
        color: "#0000FF" # Blue
      line_1:
        text: "Progress: %progress%%"
        color: "#0000FF" # Blue
      line_2:
        text: "Time left: %time_left%"
        color: "#0000FF" # Blue
      line_3_multiple:
        text: "Right click to change"
        color: "#FFFF00" # Yellow
      line_3_single:
        text: ""
        color: "#FFFF00" # Yellow
