database:
  url: "jdbc:sqlite:C:\\Users\\Max\\Documents\\GitHub\\QuestSystemPlugin\\database\\QuestSystemDB.sqlite"

npc-location:
  x: 65.5
  y: 143
  z: 57.5

npc-settings:
  type: VILLAGER
  custom-name: Quests
  custom-name-visible: true
  invulnerable: true
  ai-enabled: false
  max-health: 1000.0

npc-task:
  interval: 1
  range: 15

inventory:
  switch-page:
    success:
      sound: "BLOCK_NOTE_BLOCK_PLING"
      volume: 1
      pitch: 1
    error:
      sound: "BLOCK_NOTE_BLOCK_BASS"
      volume: 1
      pitch: 1
  next-page:
    display-name: "Next Page: %page%"
    colour: "#FFFFFF"
  prev-page:
    display-name: "Previous Page: %page%"
    colour: "#FFFFFF"
  create-quest:
    display-name: "Create Quest"
    colour: "#00FF00"
    material: BOOK
  edit-quest:
    name:
      title: "Quest Name"
      colour: "#FFCC00"
      material: "NAME_TAG"
    description:
      title: "Quest Description"
      colour: "#3399FF"
      material: "PAPER"
    objective:
      title: "Quest Objective"
      colour: "#FF6666"
      material: "PAPER"
    time-limit:
      title: "Time Limit"
      colour: "#99CC00"
      material: "CLOCK"
    rewards:
      title: "Quest Rewards"
      colour: "#FF9900"
      material: "CHEST"
    save:
      title: "Save Changes"
      colour: "#66CC99"
      material: "GREEN_WOOL"
    cancel:
      title: "Cancel Edit"
      colour: "#FF3366"
      material: "RED_WOOL"

particle-settings:
  direction:
    particle: "PORTAL"
    spacing: 0.5
    distance: 8
    count: 10
    offset-x: 0
    offset-y: 0
    offset-z: 0
    extra: 0.1
  spawn:
    particle: "FLAME"
    iterations: 10
    count: 15
    offset-x: 0.1
    offset-y: 0.5
    offset-z: 0.1
    extra: 0.02

quest-inv:
  title: "Quests"
  colour: "#FF0000"

quest-manager:
  quest:
    edit:
      title: "Right-click to edit"
      colour: "#00AAFF"
    main-colour: "#FF0000"
    reactivated:
      message: "You have reactivated the quest: "
      colour: "#FFA500"
      sound:
        name: "BLOCK_NOTE_BLOCK_PLING"
        volume: 1
        pitch: 1
    canceled:
      message: "You have canceled the quest: "
      colour: "#FF0000"
      sound:
        name: "BLOCK_NOTE_BLOCK_BASS"
        volume: 1
        pitch: 1
    accepted:
      message: "You have accepted the quest: "
      colour: "#FFA500"
      sound:
        name: "BLOCK_NOTE_BLOCK_PLING"
        volume: 1
        pitch: 1
    completed:
      message: "You have completed the quest: "
      colour: "#00FF00"
      sound:
        name: "ENTITY_PLAYER_LEVELUP"
        volume: 1
        pitch: 1
      alert:
        message: "Quest Completed"
        colour: 0x008000
        fade-in: 1000
        stay: 3000
        fade-out: 1000

    failed:
      message: "You did not complete the quest: "
      colour: "#FF0000"
      sound:
        name: "BLOCK_END_PORTAL_SPAWN"
        volume: 1
        pitch: 1
      alert:
        message: "Quest Failed"
        colour: 0xFF0000
        fade-in: 1000
        stay: 3000
        fade-out: 1000
    objective: "Your objective is to: "
    rewards:
      message: "You have received "
      colour: "#00FF00"
    time-limit: " in the given time limit of "
    click-not-started: "Click to accept"
    click-in-progress: "Click to cancel"
    click-completed: "Quest Completed"
    click-canceled: "Click to try again"
    all: "All Quests"
    status:
      in-progress:
        message: "In Progress"
        color: "#FFA500" # Orange
      completed:
        message: "Completed"
        color: "#00FF00" # Green
      canceled:
        message: "Canceled"
        color: "#FF0000" # Red
      not-started:
        message: "Not Started"
        color: "#00AAFF" # White
  lore-entries:
    empty: ""
    status-label: "Status:"
    description-label: "Description:"
    objective-label: "Objective:"
    time-limit-label: "Time limit:"
    time-left-label: "Time left:"
    rewards-label: "Rewards:"
    rewards-colour: "#00FF00"
    edit:
      title: "Right-click to edit"
      colour: "#00AAFF"
    delete:
      title: "Shift-click to delete"
      colour: "#FF0000"
      sound: "ENTITY_ITEM_BREAK"
      volume: 1
      pitch: 1
  boss-bar:
    init:
      colour: "BLUE"
      overlay: "PROGRESS"
    complete:
      colour: "GREEN"

command:
  no-player: "Only players can use this command"

quest-system:
  welcome:
    message: "Welcome back! You have active quests, click here to see them"
    colour: "#FFA500"

sign-messages:
  quests-title: "quests"
  quest-title: "quest"
  quests_sign:
    line_0:
      text: "Quests: %size%"
      color: "#000000" # Green
    line_3:
      text: ""
      color: "#00FF00" # Green
  quest_sign:
    no_quests:
      line_0:
        text: "No quests started"
        color: "#FF0000" # Red
      line_1:
        text: ""
        color: "#FF0000" # Red
      line_2:
        text: ""
        color: "#FF0000" # Red
      line_3:
        text: ""
        color: "#FF0000" # Red
    quest:
      line_0:
        text: "Quest: %name%"
        color: "#0000FF" # Blue
      line_1:
        text: "Progress: %progress%%"
        color: "#0000FF" # Blue
      line_2:
        text: "Time left: %time_left%"
        color: "#0000FF" # Blue
      line_3_multiple:
        text: "Right click to change"
        color: "#FFFF00" # Yellow
      line_3_single:
        text: ""
        color: "#FFFF00" # Yellow
