name: QuestSystem
version: 1.0.0
main: com.schotzgoblin.main.QuestSystem
description: A simple quest system for Minecraft
author: Schotzgoblin
website: https://papermc.io
api-version: '1.20'
commands:
  quests:
    description: Main command for the quest system
    usage: /<command>
    aliases: [ q ]
    children:
      manage:
        description: Main command for managing quests
        usage: /<command>
        aliases: [ qm ]
permissions:
  quests.manage.admin:
    description: Permission to manage quests
    default: op

