server_connect_timeout: 5000
enforce_secure_profile: false
remote_ping_cache: -1
forge_support: false
player_limit: -1
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeecord.command.ip
  - bungeecord.command.send
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.kick
timeout: 30000
log_commands: false
network_compression_threshold: 256
online_mode: true
servers:
  lobby:
    motd: Quest System - Lobby 1
    address: localhost:25566
    restricted: false
  lobby2:
    motd: Quest System - Lobby 2
    address: localhost:25567
    restricted: false
listeners:
- query_port: 25565
  motd: Quest System
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 1
  tab_size: 60
  force_default_server: true
prevent_proxy_connections: false
ip_forward: true
remote_ping_timeout: 5000
reject_transfers: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000
stats: fa57a4bf-6a50-4d98-ab03-ba5ab510c69f
connection_throttle_limit: 3
groups:
  md_5:
  - admin
log_pings: true
